
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    command: npm run dev
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["node", "-r", "ts-node/register", "server.ts"]
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      GLIBC_TUNABLES: "glibc.pthread.rseq=0"
  seed:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: ["node", "-r", "ts-node/register", "seed/seed.ts"]
volumes:
  mongo-data:

networks:
  default:
    name: net-todo
    external: false  # true にすると既存のネットワークを使用 