services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: npm run dev
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      GLIBC_TUNABLES: "glibc.pthread.rseq=0"
volumes:
  mongo-data:

networks:
  default:
    name: net-todo
    external: false  # true にすると既存のネットワークを使用
