services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/reactdojou
      - JWT_SECRET=your_jwt_secret_key
      - EMAIL_USER=your_email@example.com
      - EMAIL_PASS=your_email_password
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
