openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: ユーザー管理APIのドキュメント
  contact:
    name: APIサポート
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
  - name: User
    description: ユーザー関連の操作
  - name: Collection
    description: コレクション関連の操作
  - name: Question
    description: 質問関連の操作
  - name: Progress
    description: 進捗関連の操作
  - name: Result
    description: 結果関連の操作
paths:
  /:
    get:
      tags:
        - Home
      summary: ホーム画面
      description: ホーム画面を表示します。
      operationId: getHome
      responses:
        '200':
          description: ホーム画面
          content:
            application/json:
              schema:
                type: object
  /login:
    post:
      tags:
        - Auth
      summary: ログイン
      description: ログインします。
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: ログイン成功 
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: トークン
                  user:
                    type: object
                    $ref: '#/components/schemas/User'
        '401':
          description: ログイン失敗
        '404':
          description: ユーザーが見つかりません
        '500':
          description: サーバーエラー
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string  
  /signup:
    post:
      tags:
        - Auth
      summary: 新規登録
      description: 新規登録します。
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: 新規登録成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: トークン
                  user:
                    type: object
                    $ref: '#/components/schemas/User'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: ユーザーが既に存在します
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /collections:
    get:
      tags:
        - Collection
      summary: コレクションのリストを取得
      description: 登録されているすべてのコレクションのリストを取得します。
      operationId: getCollections
      responses:
        '200':
          description: コレクションのリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collection'
  /collections/{collectionId}:
    get:
      tags:
        - Collection
      summary: コレクションを取得
      description: 指定されたコレクションの詳細を取得します。
      operationId: getCollectionById
      parameters:
        - name: collectionId
          in: path
          required: true
          schema:
            type: string
            format: objectId
      responses:
        '200':
          description: コレクション
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Collection'
        '404':
          description: コレクションが見つかりません
        '500':
          description: サーバーエラー
  /questions:
    get:
      tags:
        - Question
      summary: 質問のリストを取得
      description: 登録されているすべての質問のリストを取得します。
      operationId: getQuestions
      responses:
        '200':
          description: 質問のリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
  /questions/{questionId}:
    get:
      tags:
        - Question
      summary: 質問を取得
      description: 指定された質問の詳細を取得します。
      operationId: getQuestionById
      parameters:
        - name: questionId
          in: path
          required: true
          schema:
            type: string
            format: objectId
      responses:
        '200':
          description: 質問
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Question'
        '404':
          description: 質問が見つかりません
        '500':
          description: サーバーエラー
  /questions/{questionId}/submit:
    post:
      tags:
        - Question
      summary: 質問を提出
      description: 指定された質問を提出します。
      operationId: submitQuestion
      parameters:
        - name: questionId
          in: path
          required: true
          schema:
            type: string
            format: objectId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                  description: 回答
                userId:
                  type: string
                  format: objectId
                  description: ユーザーID
                questionId:
                  type: string
                  format: objectId
                  description: 質問ID
      responses:
        '200':
          description: 質問を提出しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: 質問が見つかりません
        '500':
          description: サーバーエラー
  /progress:
    get:
      tags:
        - Progress
      summary: 進捗のリストを取得
      description: 登録されているすべての進捗のリストを取得します。
      operationId: getProgress
      responses:
        '200':
          description: 進捗のリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Progress'
  /results:
    get:
      tags:
        - Result
      summary: 結果のリストを取得
      description: 登録されているすべての結果のリストを取得します。
      operationId: getResults
      responses:
        '200':
          description: 結果のリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
  /results/{resultId}:
    get:
      tags:
        - Result
      summary: 結果を取得
      description: 指定された結果の詳細を取得します。
      operationId: getResultById
      parameters:
        - name: resultId
          in: path
          required: true
          schema:
            type: string
            format: objectId
      responses:
        '200':
          description: 結果
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Result'
        '404':
          description: 結果が見つかりません
        '500':
          description: サーバーエラー
  /progress/{progressId}:
    get:
      tags:
        - Progress
      summary: 進捗を取得
      description: 指定された進捗の詳細を取得します。
      operationId: getProgressById
      parameters:
        - name: progressId
          in: path
          required: true
          schema:
            type: string
            format: objectId
      responses:
        '200':
          description: 進捗
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Progress'
        '404':
          description: 進捗が見つかりません
        '500':
          description: サーバーエラー
components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
        - password
      properties:
        _id:
          type: string
          format: objectId
          description: ユーザーの一意識別子（MongoDB ID）
        name:
          type: string
          description: ユーザー名
        email:
          type: string
          format: email
          description: ユーザーのメールアドレス（一意）
        password:
          type: string
          format: password
          description: ユーザーのパスワード（ハッシュ化されたもの）
        createdAt:
          type: string
          format: date-time
          description: アカウント作成日時
        isEmailVerified:
          type: boolean
          default: false
          description: メール確認済みかどうか
        verificationToken:
          type: string
          nullable: true
          description: メール確認用トークン
        verificationTokenExpires:
          type: string
          format: date-time
          nullable: true
          description: メール確認用トークンの有効期限
        resetPasswordToken:
          type: string
          nullable: true
          description: パスワードリセット用トークン
        resetPasswordExpires:
          type: string
          format: date-time
          nullable: true
          description: パスワードリセット用トークンの有効期限
    Collection:
      type: object
      required:
        - name
        - description
      properties:
        _id:
          type: string
          format: objectId
          description: コレクションの一意識別子（MongoDB ID）
        name:
          type: string
          description: コレクション名
        description:
          type: string
          description: コレクションの説明
        currentIndex:
          type: integer
          default: 1
          description: 現在のインデックス
        completed:
          type: boolean
          default: false
          description: コレクションが完了したかどうか
        timesCompleted:
          type: integer
          default: 0
          description: コレクションが完了した回数
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'
          description: 質問のリスト
    Question:
      type: object
      required:
        - title
        - difficulty
        - content
        - answerCode
        - explanation
        - options
        - collectionId
      properties:
        _id:
          type: string
          format: objectId
          description: 質問の一意識別子（MongoDB ID）
        title:
          type: string
          description: 質問のタイトル
        difficulty:
          type: string
          description: 質問の難易度
        content:
          type: string
          description: 質問の内容
        sampleCode:
          type: string
          nullable: true
          description: サンプルコード
        answerCode:
          type: integer
          description: 正解のコード
        explanation:
          type: string
          description: 質問の説明
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
          description: 選択肢のリスト
        tags:
          type: array
          items:
            type: string
          description: 質問に関連するタグ
        collectionId:
          type: string
          format: objectId
          description: 関連するコレクションのID
        createdAt:
          type: string
          format: date-time
          description: 質問の作成日時
    Progress:
      type: object
      required:
        - userId
        - collectionId
        - questionOrder
        - currentIndex
        - completed
        - completedQuestions
      properties:
        _id:
          type: string
          format: objectId
          description: 進捗の一意識別子（MongoDB ID）
        userId:
          type: string
          description: ユーザーID
        collectionId:
          type: string
          description: 問題集ID
        questionOrder:
          type: array
          items:
            type: string
          description: 問題ID配列(ランダム順)
        currentIndex:
          type: integer
          description: 現在のインデックス
        completed:
          type: boolean
          description: 進捗が完了したかどうか
        completedQuestions:
          type: integer
          description: 完了した質問の数
    Result:
      type: object
      required:
        - userId
        - questionId
        - isCorrect
      properties:
        _id:
          type: string
          format: objectId
          description: 結果の一意識別子（MongoDB ID）
        userId:
          type: string
          format: objectId
          description: ユーザーID
        questionId:
          type: string
          format: objectId
          description: 質問ID
        isCorrect:
          type: boolean
          description: 回答が正解かどうか
        createdAt:
          type: string
          format: date-time
          description: 結果の作成日時
    Option:
      type: object
      required:
        - number
        - text
      properties:
        number:
          type: integer
          description: 選択肢の番号
        text:
          type: string
          description: 選択肢のテキスト
